[package]
name = "d4_builder_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true #only for when using procedural macro

[dependencies]
